@extends('frontend.layouts.app')
@section('content')
    @include('frontend.layouts.common.welcome')
    @include('frontend.layouts.common.feature')
    @include('frontend.layouts.common.buy_online')
    @include('frontend.layouts.common.payment_gateway')
    @include('frontend.layouts.common.service')
    @include('frontend.layouts.common.how_work')
@endsection